version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    commands:
      - aws cloudformation package --template-file s3://mycodepipelinebucket/template/template.yml --s3-bucket mycodepipelinebucket --output-template-file packaged-template.yml
artifacts:
  type: zip
  files:
    - packaged-template.yml
